### ISSUE TITLE
Determine sorting requirements for CRAM input/output, and add runtime checks

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#777]
It seems that hellbender can't handle input that isn't coordinate-sorted when outputting to CRAM. Let's at the very least document any limitations on input sort order -- and ideally, add some checks on startup to check sort order of read inputs at runtime.

**Comment by droazen** [comment]
For @edwardkw

**Comment by droazen** [comment]
It would also be good to figure out exactly why CRAM output fails on non-coordinate-sorted input. Does it always fail? Is it only when there's one or more unmapped reads in the input? etc.

**Comment by akiezun** [comment]
@droazen feel free to close or reassign

**Comment by droazen** [comment]
Likely fixed in the latest htsjdk -- we should confirm this.

**Comment by cmnbroad** [comment]
We cant quite verify this yet; the fixes we need just got [merged](https://github.com/samtools/htsjdk/commit/08e10f0f12af794cd17a1315e750d19c1b49d7a0) in to htsjdk yesterday, so we need to move up which I assume we'll do before alpha since I think there are other fixes we want.

**Comment by akiezun** [comment]
can you make a local jar from htsjdk master and confirm that this will work?

**Comment by cmnbroad** [comment]
Yes - I did that at the time I made the original changes.

**Comment by cmnbroad** [comment]
The write side for non-coordinate sorted CRAMs works now, but there is still a problem with reading queryname sorted input crams with unmapped reads. There is an existing [test in GATK](https://github.com/broadinstitute/gatk/blob/1ecb871ce375799f9245bf932ed5da40f045d7ec/src/test/java/org/broadinstitute/hellbender/tools/picard/sam/SortSamIntegrationTest.java#L23) for this case that is already enabled and has been passing, but only because there is [another bug](https://github.com/broadinstitute/gatk/blob/1ecb871ce375799f9245bf932ed5da40f045d7ec/src/test/java/org/broadinstitute/hellbender/tools/picard/sam/SortSamIntegrationTest.java#L37) in the test code that is masking the failure because it uses the value "outputExtension", which results in a BAM file being created. When I went to fix that as part of [re-enabling the disabled CRAM tests](https://github.com/broadinstitute/gatk/issues/1141), the verification of the queryname test output now fails. The test itself runs, but the samsEqualStringent verification fails reading the output. So the write-side issues with the presorted flag are fixed with samtools/htsjdk#368, but there is still a limitation in htsjdk for reading crams with unmapped reads that are not coordinate sorted that we need to fix/understand.

**Comment by cmnbroad** [comment]
htsjdk issue https://github.com/samtools/htsjdk/issues/404

**Comment by droazen** [comment]
This one probably cannot be done for alpha, given that it requires yet more fixes in htsjdk -- pushing to beta.

**Comment by droazen** [comment]
Actually, I take it back -- reading the issue description, all that was required here was to "determine" the limitations of cram support with respect to ordering, and that task is done. I'll close this ticket and open a new one for the issue you identified above.
